version: "3.8"
services:
  organization-frontend:
    build:
      context: ../front-end
      dockerfile: ../front-end/Dockerfile
    restart: always
    ports:
      - 80:3000
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  organization-api:
    build:
      context: ../organization-api
      dockerfile: ../organization-api/build/Dockerfile
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/search-platform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - ACCESS_JWT_SECRET=123456
      - GPT_SERVICE_URL=http://gpt-service.com
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  gpt-service:
    build:
      context: ../gpt-service
      dockerfile: ../gpt-service/build/Dockerfile
      args:
        TARGETARCH: amd64
        PROJECT: gpt-service
    environment:
      - DSN=postgres://keygen:cocacola@localhost:5432/keygen?sslmode=disable
      - PORT=8080
      - GRPC_PORT=9011
      - GPT_4_API_KEY=${GPT_4_API_KEY}
      - GOOGLE_API_KEY=${GOOGLE_API_KEY}
      - GOOGLE_CUSTOM_SEARCH_ENGINE_ID=${GOOGLE_CUSTOM_SEARCH_ENGINE_ID}
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
      - pgdata:/home/postgres/pgdata/data
    labels:
      - "service.name=timescale"
    ports:
      - 5442:5432
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  pgdata:
