version: "3.8"
services:
  organization-api:
    build:
      context: ../organization-api
      dockerfile: ../organization-api/build/Dockerfile
      args:
        PROJECT: search-platform
    restart: always
    ports:
      - 8080:8080
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/search-platform
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=123456
      - ACCESS_JWT_SECRET=123456
      - GPT_SERVICE_URL=http://gpt-service.com
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"
  postgres:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=123456
    volumes:
      - ./init_database.sh:/docker-entrypoint-initdb.d/init_database.sh
      - pgdata:/home/postgres/pgdata/data
    labels:
      - "service.name=timescale"
    ports:
      - 5442:5432
    logging:
      driver: "json-file"
      options:
        max-size: "100m"
        max-file: "5"

volumes:
  pgdata:
